export const alertsTypes = {
    SET_ALERTS: 'SET_ALERTS',
    CLEAR_ALERTS: 'CLEAR_ALERTS'
}

export const productsTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    CLEAR_UPDATE_PRODUCT: 'CLEAR_UPDATE_PRODUCT',
};

export const paginationTypes = {
    SET_PAGINATION_PAGE: 'SET_PAGINATION_PAGE',
    SET_PAGINATION_LIMIT: 'SET_PAGINATION_LIMIT',
    SET_PAGINATION_TOTAL_ITEMS: 'SET_PAGINATION_TOTAL_ITEMS',
    SET_PAGINATION_SIBLING_COUNT: 'SET_PAGINATION_SIBLING_COUNT',
};