export const alertsTypes = {
    SET_ALERTS: 'SET_ALERTS',
    CLEAR_ALERTS: 'CLEAR_ALERTS'
}

export const productsTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    CLEAR_UPDATE_PRODUCT: 'CLEAR_UPDATE_PRODUCT',
};